services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: openrouter-streamlit-chat:latest
    ports:
      - "8501:8501"
    env_file:
      - ./.env
    environment:
      STREAMLIT_SERVER_HEADLESS: "true"
      STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
      STREAMLIT_SERVER_PORT: "8501"
    restart: unless-stopped

